### ISSUE TITLE
Figure out why let-encrypt-update is failing in some vhosts

### ISSUE THREAD

**Issue by ja5087** [ocf/puppet#992]
Recently we've been getting a lot of this type of rootspam

```
An error occured!
stderr from acme-tiny:
> Parsing account key...
> Parsing CSR...
> Found domains: dev-vhost-alias.ocf.berkeley.edu
> Getting directory...
> Directory found!
> Registering account...
> Already registered!
> Creating new order...
> Order created!
> Verifying dev-vhost-alias.ocf.berkeley.edu...
> Traceback (most recent call last):
>   File "/usr/bin/acme-tiny", line 11, in <module>
>     load_entry_point('acme-tiny==20171115', 'console_scripts', 'acme-tiny')()
>   File "/usr/lib/python3/dist-packages/acme_tiny.py", line 206, in __entry_point
>     main(sys.argv[1:])
>   File "/usr/lib/python3/dist-packages/acme_tiny.py", line 192, in main
>     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
>   File "/usr/lib/python3/dist-packages/acme_tiny.py", line 131, in get_crt
>     challenge = [c for c in authorization['challenges'] if c['type'] == "http-01"][0]
> IndexError: list index out of range
> 
Traceback (most recent call last):
  File "/usr/local/bin/ocf-lets-encrypt", line 260, in <module>
    sys.exit(main())
  File "/usr/local/bin/ocf-lets-encrypt", line 252, in main
    make_request(args.domains, cert_path, args.private_key, args.dry_run)
  File "/usr/local/bin/ocf-lets-encrypt", line 169, in make_request
    assert returncode == 0, returncode
AssertionError: 1
Traceback (most recent call last):
  File "/usr/local/bin/lets-encrypt-update", line 138, in <module>
    sys.exit(main())
  File "/usr/local/bin/lets-encrypt-update", line 129, in main
    assert ret == 0, 'ocf-lets-encrypt returned {}'.format(ret)
AssertionError: ocf-lets-encrypt returned 1

```

**Comment by jvperrin** [comment]
I believe this was solved by applying the patch in https://github.com/diafygi/acme-tiny/pull/254. It was only happening for vhosts where we also recently obtained certs for them with a DNS-based challenge.
